### ISSUE TITLE
Saving As .BMP fudges color values

### ISSUE THREAD

**Issue by Phildo** [Pixen/Pixen#305]
Long story short:
Can't get pixen to save a 1x1 .BMP with pixel value 0xFF00FF. 

Repro in excruciating detail:
- Create new 1x1 pixel project.
- Use color picker to manually choose color as 0xFF00FF (magenta).
- Color in single pixel. 
- The hex preview at the bottom correctly reports R:255 G:0 B:255 A:255.
- Save as .BMP. 
- Hex dump of .BMP reports 0xFF40FF as pixel color.
- Use file in other program, reads it as 0xFF40FF.
- Load .BMP file back into pixen.
- Reports 0xFF00FF.

Specs:
Pixen 3.5.12
OSX 10.9.3

Human:
Is there something intentionally mapping to a different color space on import/export? Can that be disabled? (If so, this should REALLY be turned off by default... a program whose purpose is literally editing pixel values on a per-pixel basis shouldn't take artistic liberty come time to save the resulting data...)
Or is this a bug in the importer/exporter? (If so, Obj-C/C++ dev here- I'm happy to help. Haven't looked at the codebase, but if someone's willing to point me in the right direction I'll see what I can do)

**Comment by mattrajca** [comment]
This has been fixed for Pixen 4.

**Comment by themindoverall** [comment]
I'm still seeing this issue.  My specs:
Pixen 3.8.1
OS X 10.11
